name: whiskers

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run:
    uses: catppuccin/actions/.github/workflows/whiskers-check.yml@v1
    with:
      args: |
        templates/userChrome.tera
        templates/userContent.tera
        templates/zen-logo.tera
    secrets: inherit
